# Project Information
site_name: Math-Learning
site_description: Math-Learning 是一个编程竞赛知识整合站点，提供有趣又实用的编程竞赛知识以及其他有帮助的内容，帮助广大编程竞赛爱好者更快更深入地学习编程竞赛
site_author: Math-Learning Team
site_url: https://oi-wiki.org
strict: false

# Repository
repo_name: 'OI-wiki/OI-wiki'
repo_url: 'https://github.com/OI-wiki/OI-wiki'
edit_uri: 'https://oi-wiki.org/edit-landing/?ref='

# Copyright
copyright: 'Copyright &copy; 2016 - 2026 Math-Learning Team'

# Contents
nav:
  - 首页: index.md
  - 数学:
    - 简介: math/index.md
    - 数论基础: math/number-theory/basic.md
  - 关于:
    - 关于本站: about.md

# Theme
theme:
  name: null
  custom_dir: 'mkdocs-material/material/templates'
  static_templates:
    - 404.html
  language: 'zh'
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  include_search_page: false
  search_index_only: true
  favicon: 'favicon.ico'
  icon:
    logo: 'material/school'
  features:
    - content.action.edit
    - navigation.tabs
    - navigation.instant
    - content.code.copy
  font:
    text: 'Fira Sans'
    code: 'Fira Mono'

plugins:
- toggle-sidebar:
    theme: material
    toggle_button: all

hooks:
  - hooks/on_env.py

# Customization
extra:
  disqus: 'OI-Wiki'
  copyright: '<a href="https://creativecommons.org/licenses/by-sa/4.0/deed.zh">CC BY-SA 4.0</a> 和 <a href="https://github.com/zTrix/sata-license">SATA</a>'
  pagetime: 'on'
  manifest: 'manifest.webmanifest'
  githash: ''
  analytics:
    provider: google
    property: UA-124485594-1

extra_javascript:
  - '_static/js/math-csr.js?math-csr'
  - 'assets/vendor/mathjax/tex-mml-chtml.js?math-csr'
  - '{OIWikiFeedbackSystemFrontendJS}' # see: scripts/pre-build/install-feedback-sys-frontend.ts
  - '{OIWikiFeedbackSystemFrontendContentScript}' # see: scripts/pre-build/install-feedback-sys-frontend.ts

extra_css:
  - '_static/css/extra.css?v=16'
  # - '_static/css/offset-inject-debug.css'
  - '{OIWikiFeedbackSystemFrontendCSS}' # see: scripts/pre-build/install-feedback-sys-frontend.ts

# Extensions
markdown_extensions:
  - document-offsets-injection:
      # debug: true
  - admonition
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: ""
      slugify: !!python/name:pymdownx.slugs.uslugify
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.progressbar
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true
